INSERT INTO `cafeteriadb`.`users` (`finame`, `lname`, `email`, `password`, `role`)
VALUES (
        'Hassan',
        'Mohamed',
        'Hassan@gmail.com',
        '123456789',
        'Normal'
    ),
    (
        'Youssef',
        'Wafik',
        'YoussefWafik@gmail.com',
        '123456789',
        'Normal'
    ),
    (
        'Youssef',
        'ElGazzar',
        'YoussefElgazzar@gmail.com',
        '123456789',
        'Normal'
    ),
    (
        'Azhar',
        'ElAmir',
        'Azhar@gamil.com',
        '123456789',
        'Normal'
    ) (
        'Hassan',
        'Mohamed',
        'Hassan@gmail.com',
        '123456789',
        'Normal'
    ),
    (
        'Youssef',
        'Wafik',
        'YoussefWafik@gmail.com',
        '123456789',
        'Normal'
    ),
    (
        'Youssef',
        'ElGazzar',
        'YoussefElgazzar@gmail.com',
        '123456789',
        'Normal'
    ),
    (
        'Azhar',
        'ElAmir',
        'Azhar@gamil.com',
        '123456789',
        'Normal'
    );